import * as cheerio from 'cheerio';
import type { AnyNode, Element } from 'domhandler';

/**
 * Turns a SEC filing's raw HTML into a flat, ordered sequence of text/table
 * blocks — the structural layer sectionExtraction.ts scans for headings.
 * Deliberately a DOM walk, not a regex-over-raw-HTML pass: SEC filings are
 * generated by dozens of different vendor toolchains (Workiva, Donnelley,
 * Toppan, in-house) with wildly inconsistent tag choices for the same visual
 * structure — real semantic `<h1>`-`<h6>` tags are rare; a "heading" is
 * usually just a short, otherwise-ordinary `<p>` or `<div>`. Only a real DOM
 * walk can reliably find each block's own text without either duplicating
 * text from nested containers or losing it from unusually-nested ones.
 */

const IGNORED_TAGS = new Set(['script', 'style', 'noscript', 'head']);
// Tags treated as "block-level" for the leaf-block fallback (see walk()).
// `body`/`html` are included as a safety net for the rare filing that
// dumps text directly under <body> with no wrapping block element at all.
const BLOCK_TAGS = new Set([
  'p', 'div', 'li', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'blockquote', 'body', 'html',
]);

export type TextBlock =
  | { type: 'text'; text: string }
  | { type: 'table'; text: string };

function normalizeWhitespace(text: string): string {
  return text.replace(/ /g, ' ').replace(/[ \t]+/g, ' ').replace(/\s*\n\s*/g, '\n').trim();
}

/** Converts a `<table>` into a simple, readable text grid — one line per
 * row, cells separated by " | " — rather than either dropping tables
 * entirely or fragmenting each cell into its own disconnected text block. */
function extractTableText($: cheerio.CheerioAPI, table: Element): string | null {
  const rows: string[] = [];

  $(table)
    .find('tr')
    .each((_, tr) => {
      const cells = $(tr)
        .find('td, th')
        .map((_i, cell) => normalizeWhitespace($(cell).text()).replace(/\n/g, ' '))
        .get()
        .filter((cell) => cell.length > 0);
      if (cells.length > 0) rows.push(cells.join(' | '));
    });

  if (rows.length === 0) return null;
  return rows.join('\n');
}

/** Recursively walks the DOM in document order. Returns true if this node
 * (directly, or via a descendant) contributed a block — used so a block
 * container is only treated as a "leaf" (and has its own full text
 * extracted) when none of its children already did, avoiding both duplicate
 * and lost text regardless of how deeply filings nest their markup. */
function walk($: cheerio.CheerioAPI, node: AnyNode, blocks: TextBlock[]): boolean {
  if (node.type === 'tag') {
    const name = node.name.toLowerCase();
    if (IGNORED_TAGS.has(name)) return false;

    if (name === 'table') {
      const tableText = extractTableText($, node);
      if (tableText) {
        blocks.push({ type: 'table', text: tableText });
        return true;
      }
      return false;
    }

    let childContributed = false;
    for (const child of node.children) {
      if (walk($, child, blocks)) childContributed = true;
    }
    if (childContributed) return true;

    if (BLOCK_TAGS.has(name)) {
      const text = normalizeWhitespace($(node).text());
      if (text.length > 0) {
        blocks.push({ type: 'text', text });
        return true;
      }
    }
    return false;
  }

  if ('children' in node && Array.isArray((node as { children?: AnyNode[] }).children)) {
    let childContributed = false;
    for (const child of (node as { children: AnyNode[] }).children) {
      if (walk($, child, blocks)) childContributed = true;
    }
    return childContributed;
  }

  return false;
}

/** Parses a filing's HTML into an ordered list of text/table blocks. */
export function extractTextBlocks(html: string): TextBlock[] {
  const $ = cheerio.load(html);
  const blocks: TextBlock[] = [];

  $.root()
    .get()
    .forEach((root) => walk($, root, blocks));

  return blocks;
}
