'use client';

import type { CitedItem, RiskItem } from '@/lib/ai/schema';
import type { FilingAnalysisResponse, FilingSectionResponse } from '@/lib/api/filings';
import { CitationBadge } from './CitationBadge';

function resolveAnchor(sections: FilingSectionResponse[], sectionLabel: string): string | null {
  const match = sections.find((s) => s.sectionType === sectionLabel) ?? sections.find((s) => s.title === sectionLabel);
  return match?.anchor ?? null;
}

const RISK_CATEGORY_LABELS: Record<string, string> = {
  financial: 'Financial',
  operational: 'Operational',
  regulatory: 'Regulatory',
  legal: 'Legal',
  competitive: 'Competitive',
  macroeconomic: 'Macroeconomic',
  liquidity: 'Liquidity',
  governance: 'Governance',
};

function CitedItemList({ items, sections }: { items: CitedItem[]; sections: FilingSectionResponse[] }) {
  if (items.length === 0) {
    return <p className="text-ink/40 text-xs">None identified in this filing.</p>;
  }
  return (
    <ul className="space-y-3">
      {items.map((item, index) => (
        <li key={index}>
          <p className="text-ink text-sm">{item.description}</p>
          <CitationBadge section={item.source.section} excerpt={item.source.excerpt} anchor={resolveAnchor(sections, item.source.section)} />
        </li>
      ))}
    </ul>
  );
}

function RiskList({ risks, sections }: { risks: RiskItem[]; sections: FilingSectionResponse[] }) {
  if (risks.length === 0) {
    return <p className="text-ink/40 text-xs">No notable risks flagged in this filing.</p>;
  }
  return (
    <ul className="space-y-3">
      {risks.map((risk, index) => (
        <li key={index}>
          <div className="flex items-start justify-between gap-2">
            <p className="text-ink text-sm">{risk.description}</p>
            <span className="border-ink/15 text-ink/60 shrink-0 rounded border px-1.5 py-0.5 text-[10px] font-medium uppercase tracking-wide">
              {RISK_CATEGORY_LABELS[risk.category] ?? risk.category}
            </span>
          </div>
          <CitationBadge section={risk.source.section} excerpt={risk.source.excerpt} anchor={resolveAnchor(sections, risk.source.section)} />
        </li>
      ))}
    </ul>
  );
}

interface AnalysisSectionProps {
  title: string;
  children: React.ReactNode;
}
function AnalysisSection({ title, children }: AnalysisSectionProps) {
  return (
    <div className="border-ink/10 bg-paper rounded-xl border p-4">
      <h3 className="text-ink text-sm font-semibold">{title}</h3>
      <div className="mt-3">{children}</div>
    </div>
  );
}

interface AnalysisPanelProps {
  analysis: FilingAnalysisResponse;
  sections: FilingSectionResponse[];
}

export function AnalysisPanel({ analysis, sections }: AnalysisPanelProps) {
  if (analysis.status === 'FAILED') {
    return (
      <div className="border-ink/10 bg-paper mt-3 rounded-xl border p-6">
        <p className="text-sm font-medium text-red-700">Analysis generation failed.</p>
        <p className="text-ink/60 mt-1 text-xs">{analysis.error ?? 'An unknown error occurred.'}</p>
        <p className="text-ink/40 mt-2 text-xs">
          The original filing and its extracted sections below remain fully available.
        </p>
      </div>
    );
  }

  return (
    <div className="mt-3 space-y-4">
      <AnalysisSection title="Executive Summary">
        <p className="text-ink text-sm leading-relaxed">{analysis.summary}</p>
      </AnalysisSection>

      <AnalysisSection title="Key Changes">
        <CitedItemList items={analysis.keyChanges} sections={sections} />
      </AnalysisSection>

      <AnalysisSection title="Risk Flags">
        <RiskList risks={analysis.risks} sections={sections} />
      </AnalysisSection>

      <AnalysisSection title="Management Commentary">
        <CitedItemList items={analysis.managementCommentary} sections={sections} />
      </AnalysisSection>

      <AnalysisSection title="Liquidity & Capital Allocation">
        <CitedItemList items={analysis.capitalAllocation} sections={sections} />
      </AnalysisSection>

      <AnalysisSection title="Accounting / Reporting Changes">
        <CitedItemList items={analysis.accountingChanges} sections={sections} />
      </AnalysisSection>

      <p className="text-ink/40 text-xs">
        Generated by {analysis.model} on {new Date(analysis.generatedAt).toLocaleString()}. This is an AI-generated
        research aid, not investment advice — every item above cites the filing text it was drawn from.
      </p>
    </div>
  );
}
