import { ReportSection } from './ReportSection';

/** "If critical data is stale, display a warning" — the per-section
 * warnings aggregateResearchContext.ts collects (never silently dropped)
 * surface here, plus the standing disclaimer every exported report carries. */
export function MethodologyNote({ warnings, ticker }: { warnings: string[]; ticker: string }) {
  return (
    <ReportSection id="methodology" title="Methodology" defaultOpen={false}>
      {warnings.length > 0 && (
        <div>
          <p className="text-ink/40 mb-1 text-[10px] font-medium uppercase tracking-wide">Data Notes</p>
          <ul className="text-ink/60 list-inside list-disc space-y-0.5 text-xs">
            {warnings.map((w, i) => (
              <li key={i}>{w}</li>
            ))}
          </ul>
        </div>
      )}
      <p className="text-ink/50 text-xs leading-relaxed">
        This report is generated by Atlas Research by combining its own deterministic financial, DCF, comparable-company,
        SEC filing, and earnings-call data with an AI model that organizes and explains — but never calculates or
        invents — that data. It is not personalized investment advice and does not constitute a recommendation to buy,
        sell, or hold any security.{' '}
        <a href={`/company/${ticker}/report/methodology`} className="text-accent hover:underline">
          Full methodology →
        </a>
      </p>
    </ReportSection>
  );
}
